[workspace]
members = [
  "programs/personal-savings",
  "programs/timelock",
  "programs/prize-savings",
  "programs/savings-circles",
  "programs/microloans",
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "Apache-2.0"
rust-version = "1.89"

[workspace.dependencies]
anchor-lang = "=1.2.0"
anchor-spl = { version = "=1.2.0", default-features = false, features = ["associated_token", "token", "token_2022"] }

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1

[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1
