import type { FC } from 'react'
import { Link } from 'react-router-dom'
import { ArrowDownUp, ArrowRight, CheckCircle2, LockKeyhole, ShieldCheck, Trophy, Users, WalletCards, type LucideIcon } from 'lucide-react'
import NavBar from '../components/NavBar'
import Footer from '../components/Footer'
import { SEO } from '../components/SEO'
import { IMG } from '../lib/images'
import { USDC_MAINNET_MINT_ADDRESS } from '../lib/solana'

export default function Landing() {
  return <div className="bg-white text-ink-900 overflow-x-hidden">
    <SEO title="Savings on Solana" description="A full StashPot savings platform built on a self-custodial Solana mainnet wallet, with contract-dependent products gated until reviewed deployment." canonical="https://stashpot-frontendd.vercel.app/" />
    <NavBar />
    <section className="relative min-h-screen flex items-center pt-16"><div className="absolute inset-0"><img src={IMG.hero} alt="Building personal savings" className="w-full h-full object-cover" loading="eager" fetchPriority="high" /><div className="absolute inset-0 hero-overlay" /></div><div className="relative z-10 max-w-7xl mx-auto px-6 lg:px-10 py-24 w-full"><div className="max-w-4xl"><div className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full bg-white/95 border border-accent-200 mb-8 shadow-soft"><ShieldCheck size={13} className="text-accent-600" /><span className="text-xs font-semibold text-accent-800">Wallet layer live on Solana mainnet</span></div><h1 className="text-5xl sm:text-6xl lg:text-7xl xl:text-[5.2rem] font-bold tracking-tightest text-ink-950 leading-[1.02] mb-6 text-balance">Save with purpose.<br /><span className="gradient-brand">Keep financial truth on-chain.</span></h1><p className="text-lg lg:text-xl text-ink-800 max-w-2xl mb-9 leading-relaxed font-medium">Fund through Jupiter, build savings pots and TimeLocks, and prepare for prize savings, Circles and activity-based microloans—without fake balances.</p><div className="flex flex-wrap gap-3"><Link to="/dashboard" className="inline-flex items-center gap-2 px-5 py-3 rounded-lg bg-gradient-to-r from-royal-600 to-royal-700 text-white text-sm font-semibold shadow-royal"><WalletCards size={16} /> Open StashPot <ArrowRight size={14} /></Link><Link to="/fund" className="inline-flex items-center gap-2 px-5 py-3 rounded-lg bg-white border border-ink-300 text-sm font-semibold"><ArrowDownUp size={16} /> Fund wallet</Link></div><div className="mt-10 flex flex-wrap gap-x-7 gap-y-2 text-sm text-ink-700 font-medium"><span className="inline-flex items-center gap-1.5"><CheckCircle2 size={15} className="text-accent-600" /> Native Circle USDC</span><span className="inline-flex items-center gap-1.5"><CheckCircle2 size={15} className="text-accent-600" /> No fake credits</span><span className="inline-flex items-center gap-1.5"><CheckCircle2 size={15} className="text-accent-600" /> Contract-gated funds</span></div></div></div></section>
    <section id="features" className="py-24 bg-ink-50"><div className="max-w-7xl mx-auto px-6 lg:px-10"><div className="max-w-2xl mb-12"><p className="text-royal-700 text-sm font-semibold mb-2">One integrated savings product</p><h2 className="text-4xl lg:text-5xl font-bold tracking-tighter-2">Fund, save and build verified history</h2></div><div className="grid md:grid-cols-2 lg:grid-cols-4 gap-5"><Feature icon={WalletCards} title="Savings Pots" text="Named flexible savings with verifiable deposits and withdrawals." /><Feature icon={LockKeyhole} title="TimeLockr" text="On-chain time rules that the frontend cannot bypass." /><Feature icon={Trophy} title="Prize Savings" text="Principal isolated from separately realized yield rewards." /><Feature icon={Users} title="Circles & loans" text="Reliable contributions build explainable internal eligibility." /></div></div></section>
    <section id="how" className="py-24"><div className="max-w-5xl mx-auto px-6 lg:px-10 grid lg:grid-cols-2 gap-12 items-center"><div><p className="text-royal-700 text-sm font-semibold mb-2">How it works</p><h2 className="text-4xl font-bold tracking-tight mb-5">The blockchain is the source of truth</h2><p className="text-ink-600 leading-relaxed mb-6">Wallet funds come from native USDC accounts. Deposited savings will come from isolated program vaults. A backend may index names and history, but cannot create financial balances.</p><Link to="/dashboard" className="inline-flex items-center gap-2 text-royal-700 font-semibold">Explore the product <ArrowRight size={15} /></Link></div><div className="rounded-2xl bg-ink-950 text-white p-7 shadow-soft-lg"><p className="text-xs uppercase tracking-wider text-ink-400 mb-3">Official Solana USDC mint</p><code className="text-sm break-all text-accent-300">{USDC_MAINNET_MINT_ADDRESS}</code><p className="text-sm text-ink-300 mt-5">Only this Circle-issued mint is counted or accepted by StashPot programs.</p></div></div></section>
    <section id="security" className="py-24 bg-royal-950 text-white"><div className="max-w-5xl mx-auto px-6 lg:px-10 text-center"><ShieldCheck size={44} className="mx-auto text-accent-400 mb-5" /><h2 className="text-4xl font-bold mb-5">No seed phrase. No private key. Explicit vault rules.</h2><p className="text-white/75 max-w-2xl mx-auto text-lg">Your wallet signs every action. Funds deliberately deposited into StashPot programs are controlled only by their disclosed on-chain withdrawal rules.</p></div></section>
    <section id="faq" className="py-24"><div className="max-w-4xl mx-auto px-6 lg:px-10"><h2 className="text-4xl font-bold mb-10">Current status</h2><div className="space-y-4"><Faq q="Can I use real USDC now?" a="Yes for wallet funding and Jupiter swaps. The app is fixed to Solana mainnet and reads exact native USDC." /><Faq q="Can I deposit into a savings program now?" a="Not yet. Financial program actions remain unavailable until locally/devnet-tested programs are reviewed, deployed by you, and verified." /><Faq q="Is StashPot only a wallet?" a="No. Every original product area is present and its real architecture is being implemented; unavailable actions are labeled instead of simulated." /></div></div></section>
    <Footer />
  </div>
}

const Feature: FC<{ icon: LucideIcon; title: string; text: string }> = ({ icon: Icon, title, text }) => <div className="rounded-2xl border border-ink-200 bg-white p-6 shadow-soft"><Icon size={21} className="text-royal-700" /><h3 className="text-lg font-bold mt-4">{title}</h3><p className="text-sm text-ink-600 mt-2 leading-relaxed">{text}</p></div>
const Faq: FC<{ q: string; a: string }> = ({ q, a }) => <div className="rounded-xl border border-ink-200 p-5"><h3 className="font-bold mb-2">{q}</h3><p className="text-sm text-ink-600 leading-relaxed">{a}</p></div>
